name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging, ci-cd ]
  pull_request:
    branches: [ main, staging ]

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  lint:
    name: Linting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 (Saran Scorecard)
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@85f761ba6e0f443b04443f6766961122227ca049 # v7.1.0 (Saran Scorecard)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          LINTER_RULES_PATH: .github/checks
          JAVA_FILE_NAME: 'google-check.xml'

  # 2. TESTING & SONAR
  test:
    name: Unit Testing
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Java toolchain
        uses: actions/setup-java@3a473e33f6786ece99446d655f4c40590897c83c # v4.4.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test sonar --console=plain --info

  deploy:
    name: Dummy Deployment
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
    steps:
      - name: Deployment Simulation
        run: |
          echo "Linting and Tests Passed!"
          echo "Quality Gate Secured. Deploying Achievement Module..."